# Generated by Django 4.0.5 on 2022-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
